/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASpace: typeof import('ant-design-vue/es')['Space']
    Breadcrumb: typeof import('./src/components/Breadcrumb/Breadcrumb.vue')['default']
    Card: typeof import('./src/components/common/Card/Card.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/confirm-dialog/ConfirmDialog.vue')['default']
    DistrictSelect: typeof import('./src/components/common/district-select/DistrictSelect.vue')['default']
    DistrictTree: typeof import('./src/components/common/district-tree/DistrictTree.vue')['default']
    ListTable: typeof import('./src/components/common/ListTable/ListTable.vue')['default']
    MapTool: typeof import('./src/components/MapToolList/map-tool.vue')['default']
    MapToolBox: typeof import('./src/components/MapToolBox/map-tool-box.vue')['default']
    NumberInpute: typeof import('./src/components/common/NumberInput/NumberInpute.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/common/SearchFilter/SearchFilter.vue')['default']
  }
}
